In [15]:
"""
SVD: A = U@S@V.T
This file answers the simple question:
    since A.T@A is symmetric and A.T@A = V@S.T@S@V.T, then why isn't A = S@V.T ?
The answer is simply A^2 = B^2 does not imply A = B!
"""
import numpy as np

In [19]:
"""
Counter-example where A != S@V.T
Replace with the next line to see that in some cases A can be S@V.T
"""
A = np.array([[7,1],[5,5],[0,0]])
#A = np.array([[ 8.48528137,  4.24264069],[-1.41421356,  2.82842712],[ 0.        ,  0.        ]])
print("A = \n", A)

A = 
 [[ 8.48528137  4.24264069]
 [-1.41421356  2.82842712]
 [ 0.          0.        ]]


In [20]:
A2 = A.T @ A
print("A.T @ A = \n", A2)

A.T @ A = 
 [[73.99999992 32.00000002]
 [32.00000002 26.        ]]


In [21]:
L, V = np.linalg.eig(A2)
print("V = \n", V)

V = 
 [[ 0.89442719 -0.4472136 ]
 [ 0.4472136   0.89442719]]


In [22]:
S = np.array([[L[0]**0.5, 0],[0, L[1]**0.5],[0, 0]])
print("S = \n", S)

S = 
 [[9.48683298 0.        ]
 [0.         3.16227765]
 [0.         0.        ]]


In [23]:
V@S.T@S@V.T

array([[73.99999992, 32.00000002],
       [32.00000002, 26.        ]])

In [24]:
"""
S@V.T != A 
"""
S@V.T

array([[ 8.48528137,  4.24264069],
       [-1.41421356,  2.82842712],
       [ 0.        ,  0.        ]])